In [1]:
import joblib
import pandas as pd
import numpy as np
import random

In [2]:

loaded_model = joblib.load(r"C:\Users\Avijit\Desktop\CANCER_PREDICTION\models\model.pkl")

In [3]:
feature_names = ['Age', 'Gender', 'BMI', 'Smoking', 'GeneticRisk', 'PhysicalActivity', 'AlcoholIntake', 'CancerHistory']

def predict_cancer(input_data):
    input_df = pd.DataFrame([input_data], columns=feature_names)
    prediction = loaded_model.predict(input_df)[0]
    probability = loaded_model.predict_proba(input_df)[0][1]
    return prediction, probability

def get_user_input_jupyter():
    print("\nEnter the following features:")
    user_data = {}
    for feature in feature_names:
        while True:
            try:
                value = float(input(f"Enter {feature}: "))
                user_data[feature] = value
                break
            except ValueError:
                print("Invalid input.")
    return list(user_data.values())

def get_random_input():
    random_data = {
        'Age': random.randint(18, 80),
        'Gender': random.choice([0, 1]),
        'BMI': round(random.uniform(15, 40), 2),
        'Smoking': random.choice([0, 1]),
        'GeneticRisk': random.randint(0, 1),
        'PhysicalActivity': round(random.uniform(0, 10), 2),
        'AlcoholIntake': round(random.uniform(0, 5), 2),
        'CancerHistory': random.choice([0, 1])
    }
    return list(random_data.values()), random_data

In [4]:
def main():
    while True:
        print("\nChoose an input method:")
        print("1. User Input")
        print("2. Random Input")
        print("3. Exit")

        choice = input("Enter your choice (1, 2, or 3): ")

        if choice == '1':
            input_values = get_user_input_jupyter()
            prediction, probability = predict_cancer(input_values)
            input_dict = dict(zip(feature_names, input_values))
            print("\n--- Input Data ---")
            display(pd.DataFrame([input_dict]))
            print("\n--- Prediction ---")
            print(f"Predicted Diagnosis: {'Positive' if prediction == 1 else 'Negative'}")
            print(f"Probability of Positive Diagnosis: {probability:.4f}")

        elif choice == '2':
            input_values, input_dict = get_random_input()
            prediction, probability = predict_cancer(input_values)
            print("\n--- Random Input Data ---")
            display(pd.DataFrame([input_dict]))
            print("\n--- Prediction ---")
            print(f"Predicted Diagnosis: {'Positive' if prediction == 1 else 'Negative'}")
            print(f"Probability of Positive Diagnosis: {probability:.2f}")

        elif choice == '3':
            print("Exiting...")
            break

        else:
            print("Invalid choice.")

In [5]:
if __name__ == "__main__":
    main()

Choose an input method:
1. User Input
2. Random Input
3. Exit

--- Random Input Data ---

,Age,Gender,BMI,Smoking,GeneticRisk,PhysicalActivity,AlcoholIntake,CancerHistory
0,41,1,28.79,1,0,7.94,1.59,1

--- Prediction ---
Predicted Diagnosis: Positive
Probability of Positive Diagnosis: 0.81

Choose an input method:
1. User Input
2. Random Input
3. Exit

--- Random Input Data ---

,Age,Gender,BMI,Smoking,GeneticRisk,PhysicalActivity,AlcoholIntake,CancerHistory
0,32,1,19.93,1,0,3.3,1.65,1

--- Prediction ---
Predicted Diagnosis: Positive
Probability of Positive Diagnosis: 0.50

Choose an input method:
1. User Input
2. Random Input
3. Exit
Exiting...